### ISSUE TITLE
Complete/expand with additional combinations

### ISSUE THREAD

**Issue by danielsjf** [hadley/tidyr#121]
Is it possible to implement a way to include permutations using more than just the options provided in the data frame?

Now it works like this:

    > data.frame(a=c(1,2),b=c(3,4)) %>%
        expand(a,b)
    Source: local data frame [4 x 2]
          a     b
      (dbl) (dbl)
    1     1     3
    2     1     4
    3     2     3
    4     2     4

But it would be nice to have something like this:

    > data.frame(a=c(1,2),b=c(3,4)) %>%
        expand(a,b=c(3:5))
    Source: local data frame [6 x 2]
          a     b
      (dbl) (dbl)
    1     1     3
    2     1     4
    3     1     5
    4     2     3
    5     2     4
    6     2     5

The exact same problem holds for complete.

**Comment by hadley** [comment]
Hmmm, I'm not sure it's possible to make this work in `expand()` because it currently (for good reason), has select-like semantics, and there's no reliable way to tell the difference between these two calls:

```R
df %>% expand(b = a)
a <- 1:4
df %>% expand(b = a)
```

I think that suggests we need another variant on `expand()`. I suspect we also need `expand_grid()` which doesn't use data at all (I still find myself reaching for `expand.grid()` when I want to create completely new datasets)
