### ISSUE TITLE
No info on latest version

### ISSUE THREAD

**Issue by pssguy** [hadley/tidyr#157]
Kinda nitpicking after all you do but I see 0.4.0 has been released on CRAN and I'm sure it has some great enhancements but there does not seem to be a News  feature documenting them. 

Any chance of incorporating that in future 
ps I think same applies to other packages eg dplyr

**Comment by jennybc** [comment]
Here on github, you can read NEWS: <https://github.com/hadley/tidyr/blob/master/NEWS.md>.

**Comment by pssguy** [comment]
tx. Any idea why it isn't on RStudio. Is it failing a CRAN requirement?

**Comment by jennybc** [comment]
From watching `devtools`, I gather Hadley recently changed the treatment of `NEWS.md` and it's possible that the recent `tidyr` update was a learning case. Specifically, I don't think it's intentional that `NEWS.md` is Rbuildignored here (it shouldn't be: https://github.com/hadley/devtools/commit/7b662216521e3945aa3dbb2f99e64fe88f51f02e). Suspect that explains why NEWS not present in the `tidyr` on CRAN.

**Comment by pssguy** [comment]
It seems to be consistent across all packages though dplyr, readr, purrr ...
Just would be handy to open in RStudio. Small point though

**Comment by jennybc** [comment]
I think the fact that `NEWS.md` is accepted by CRAN is semi-recent (and maybe not true for release, only devel?) and even more recently accounted for in the `devtools` workflows, which is undoubtedly used on all those packages above.

<https://github.com/hadley/devtools/issues/957>

I think time will take care of it. In meantime, all of them have detailed `NEWS.md` on github.
