### ISSUE TITLE
All verbs need method for grouped_df

### ISSUE THREAD

**Issue by hadley** [hadley/tidyr#81]
* [x] nest
* [x] unnest
* [x] spread
* [x] gather
* [x] separate
* [x] extract
* [x] unite
* [x] fill
* [x] expand

**Comment by npjc** [comment]
@hadley hopefully I put this in the right place (instead of a separate issue):

#### `replace_na()` should respect grouping:

``` r
library(dplyr)
library(tidyr)
df <- data_frame(x = c("a", "b", "b"), idx = c(1, 1:2), y = c("only-obs", "obs-1","obs-2"))
df
#> Source: local data frame [3 x 3]
#> 
#>       x   idx        y
#>   (chr) (dbl)    (chr)
#> 1     a     1 only-obs
#> 2     b     1    obs-1
#> 3     b     2    obs-2
```

notice that for `x == "a"` there is only one y observation: `"only-obs"`.

``` r
df %>% complete(x, idx)
#> Source: local data frame [4 x 3]
#> 
#>       x   idx        y
#>   (chr) (dbl)    (chr)
#> 1     a     1 only-obs
#> 2     a     2       NA
#> 3     b     1    obs-1
#> 4     b     2    obs-2
```

I wish that `replace_na()` would respect grouping so that I could compute the value to replace with based on the current group. In this case you get the desired outcome because it is taking the first one (hence warning).

``` r
df %>% 
  complete(x, idx) %>% 
  group_by(x) %>% 
  replace_na(list(y = .$y[!is.na(.$y)]))
#> Warning in data[[var]][is.na(data[[var]])] <- replace[[var]]: number of
#> items to replace is not a multiple of replacement length
#> Source: local data frame [4 x 3]
#> 
#>       x   idx        y
#>   (chr) (dbl)    (chr)
#> 1     a     1 only-obs
#> 2     a     2 only-obs
#> 3     b     1    obs-1
#> 4     b     2    obs-2
```

**Comment by hadley** [comment]
@npjc can you please create a new issue? It's not really related

**Comment by npjc** [comment]
moved comment into separate issue (#101.)
